//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _17._6_HomeWork_WPFapp_shop_base_usses_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsInfo
    {
        public int id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public Nullable<double> phonenumber { get; set; }
        public string email { get; set; }
    }
}
