//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _17._6_HomeWork_WPFapp_shop_base_usses_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsInfo
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public int Code { get; set; }
        public string Title { get; set; }
    }
}
